name: Update Homebrew formulae
on:
  push:
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with only the 'public_repo' scope 
          token: ${{secrets.TOKEN}}
          # Optional, defaults to homebrew/core
          tap: integzz/homebrew-chinese
          # Formula name, required
          formula: julia-linux
          # Optional, will be determined automatically
          tag: ${{github.ref}}
          # Optional, will be determined automatically
          revision: ${{github.sha}}
          # Optional, if don't want to check for already open PRs
          force: false # true
